// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	galery "ikuzports/features/galery"

	mock "github.com/stretchr/testify/mock"
)

// GaleryRepo is an autogenerated mock type for the RepositoryInterface type
type GaleryRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: input, id
func (_m *GaleryRepo) Create(input galery.Core, id int) error {
	ret := _m.Called(input, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(galery.Core, int) error); ok {
		r0 = rf(input, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *GaleryRepo) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *GaleryRepo) GetAll() ([]galery.Core, error) {
	ret := _m.Called()

	var r0 []galery.Core
	if rf, ok := ret.Get(0).(func() []galery.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]galery.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *GaleryRepo) GetById(id int) (galery.Core, error) {
	ret := _m.Called(id)

	var r0 galery.Core
	if rf, ok := ret.Get(0).(func(int) galery.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(galery.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: input, id
func (_m *GaleryRepo) Update(input galery.Core, id int) error {
	ret := _m.Called(input, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(galery.Core, int) error); ok {
		r0 = rf(input, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGaleryRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewGaleryRepo creates a new instance of GaleryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGaleryRepo(t mockConstructorTestingTNewGaleryRepo) *GaleryRepo {
	mock := &GaleryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
